### ISSUE TITLE
Exporting record selector exposes Cache implementation

### ISSUE THREAD

**Issue by spl** [DanBurton/io-memoize#2]
Since you export the record selector `fetch`, one can use that to construct `Cache` values that defy the invariant defined by `cache`:

``` haskell
*Control.Concurrent.Cache> c <- newCache
*Control.Concurrent.Cache> let c' = c { fetch = \_ -> (return undefined :: IO String) }
*Control.Concurrent.Cache> fetch c' getLine
"*** Exception: Prelude.undefined
```

Consequently, `Cache` is not really as abstract as one might expect.

**Comment by DanBurton** [comment]
Oh, nasty. Thanks for pointing that out. I'll fix that right away. There are some other tweaks I had in mind about the internal representation/implementation of `Cache` and this is a great reason to do those as well.
