### ISSUE TITLE
Simplify fetch

### ISSUE THREAD

**Issue by sol** [DanBurton/io-memoize#3]
``` haskell
fetch :: Cache a -> IO a -> IO a
fetch (Cache var) action = modifyMVar var $ \m -> case m of
  Just a -> return (m, a)
  Nothing -> do
    a <- action
    return (Just a, a)
```

**Comment by DanBurton** [comment]
In theory, read is cheaper than modify, which is why fetch is written the way it is currently: so that cache hits will (hopefully) be slightly faster. I haven't benchmarked it or anything, though, so I could be completely wrong on this.
